spring:
  application:
    name: demo

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 0

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
            time-zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect

        format_sql: true

server:
  port: 8080
  tomcat:
    max-swallow-size: -1

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:true}
  swagger-ui:
    enabled: ${SPRINGDOC_ENABLED:true}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

ai:
  provider: gemini
  api-key: ${GOOGLE_API_KEY}

weather:
  api:
    key: ${WEATHER_API_KEY}
    url: https://api.openweathermap.org/data/2.5/weather

data:
  seeder:
    enabled: ${DATA_SEEDER_ENABLED:false}

storage:
  root-dir: ${STORAGE_ROOT:/storage}
  avatar-max-size-mb: 20

api:
  security:
    skip-paths:
      - /swagger-ui.html
      - /v3/api-docs
      - /swagger-ui/**
      - /swagger-ui/index.html

    token:
      secret: ${JWT_SECRET:my-secret}
      refresh-secret: ${JWT_REFRESH_SECRET:my-refresh-secret}
      expiration: ${JWT_TIME:2}

    gemini:
      api-key: ${GOOGLE_API_KEY}