spring:
  application:
    name: demo

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jbdc:
            time-zone: UTC
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

ai:
  provider: gemini
  api-key: ${GOOGLE_API_KEY}

api:
  security:
    skip-paths:
      - /swagger-ui.html
      - /v3/api-docs
      - /swagger-ui/**
      - /swagger-ui/index.html

    token:
      secret: ${JWT_SECRET:my-secret}
      refresh-secret: ${JWT_REFRESH_SECRET:my-refresh-secret}
      expiration: ${JWT_TIME:2}

    gemini:
      api-key: ${GOOGLE_API_KEY}